export enum IntentType {
  BOOK_APPOINTMENT = 'BOOK_APPOINTMENT',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
  VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS',
  CHECK_SLOTS = 'CHECK_SLOTS',
  FALLBACK = 'FALLBACK',
}
