export enum IntentType {
  BOOK_APPOINTMENT = 'BOOK_APPOINTMENT',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
  RESCHEDULE_APPOINTMENT = 'RESCHEDULE_APPOINTMENT',
  VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS',
  CHECK_SLOTS = 'CHECK_SLOTS',
  ESCALATE_TO_AGENT = 'ESCALATE_TO_AGENT',
  FALLBACK = 'FALLBACK',
}
